// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ordfdszlhswivntwuvxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yZGZkc3psaHN3aXZudHd1dnhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MzM2NzMsImV4cCI6MjA2MDQwOTY3M30.D0FzXYKRdh-kQrTMrgdMAnlCkwRzW15A0FAaRxZ5rbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);